/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Lab1_1Buffers (
  input [7:0] SW,
  output [7:0] LED
);
  assign LED = SW;
endmodule
