set_property SRC_FILE_INFO {cfile:C:/Users/scott/Documents/GitHub/ENES246/-1Buffers/VoltageControlledBuffer/VoltageControlledBuffer/vcb/vcb.srcs/constrs_1/imports/VoltageControlledBuffer/Nexys4DDR_Master.xdc rfile:../../../vcb.srcs/constrs_1/imports/VoltageControlledBuffer/Nexys4DDR_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { sw0 }]; #IO_L24N_T3_RS0_15 Sch=sw[0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L16   IOSTANDARD LVCMOS33 } [get_ports { sw1 }]; #IO_L3N_T0_DQS_EMCCLK_14 Sch=sw[1]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H17   IOSTANDARD LVCMOS33 } [get_ports { LED }]; #IO_L18P_T2_A24_15 Sch=led[0]
